###
GET http://localhost:5288/games

###
GET http://localhost:5288/games/1

###
POST http://localhost:5288/games
Content-Type: application/json

{
  "Name": "Super Mario",
  "Genre":"Platformer",
  "Price": 59.99,
  "ReleaseDate": "2026-10-20"
}