###
GET http://localhost:5288/games

###
GET http://localhost:5288/games/1

###
POST http://localhost:5288/games
Content-Type: application/json

{
  "Name": "Super Mario",
  "Genre":"Platformer",
  "Price": 59.99,
  "ReleaseDate": "2026-10-20"
}

###
//validation example
POST http://localhost:5288/games
Content-Type: application/json

{
  "Name": "",
  "Genre":"Platformer",
  "Price": 59.99,
  "ReleaseDate": "2026-10-20"
}

###
//Maximum length validation example
POST http://localhost:5288/games    
Content-Type: application/json

{
  "Name": "This game name is way too long to be accepted by the validation rules set in the CreateGameDto class",
  "Genre":"Platformer",
  "Price": 59.99,
  "ReleaseDate": "2026-10-20"
}

###
PUT http://localhost:5288/games/1
Content-Type: application/json

 {
    "id": 1,
    "name": "The Legend of Zelda: Updated",
    "genre": "Action-Adventure",
    "price":5.99,
    "releaseDate": "2023-05-15"
  }

###
DELETE http://localhost:5288/games/2